/*
 * Copyright 2017 trivago GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.trivago.rta.features;

import com.trivago.rta.vo.SingleScenarioFeature;

import java.util.Date;

public class FeatureFileContentRenderer {

    private static final String FEATURE = "Feature: ";
    private static final String SCENARIO = "Scenario: ";
    private static final String GENERATED_BY_CUCABLE_MESSAGE = "# Generated by Cucable, ";

    /**
     * Get the complete content that can be written to a valid feature file.
     *
     * @return the feature file content.
     */
    public String getRenderedFeatureFileContent(SingleScenarioFeature singleScenarioFeature) {
        StringBuilder renderedContent = new StringBuilder();

        // add feature name
        renderedContent
                .append(FEATURE).append(singleScenarioFeature.getFeatureName())
                .append(System.lineSeparator()).append(System.lineSeparator());

        // add tags
        for (String tag : singleScenarioFeature.getTags()) {
            renderedContent.append(tag).append(System.lineSeparator());
        }

        // add scenario name with keywords
        renderedContent.append(SCENARIO)
                .append(singleScenarioFeature.getName()).append(System.lineSeparator());

        // add steps
        for (int i = 0; i < singleScenarioFeature.getSteps().size(); i++) {
            String stepText = singleScenarioFeature.getSteps().get(i);
            String keyword = singleScenarioFeature.getKeywords().get(i);
            renderedContent.append(keyword).append(" ").append(stepText).append(System.lineSeparator());
        }

        renderedContent.append(System.lineSeparator())
                .append(GENERATED_BY_CUCABLE_MESSAGE).append(new Date())
                .append(System.lineSeparator());

        return renderedContent.toString();
    }
}
