package com.trivago.rta.features;

import com.trivago.rta.vo.SingleScenario;
import com.trivago.rta.vo.Step;
import org.junit.Before;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class FeatureFileContentRendererTest {

    private FeatureFileContentRenderer featureFileContentRenderer;

    @Before
    public void setup() {
        featureFileContentRenderer = new FeatureFileContentRenderer();
    }

    @Test
    public void getRenderedFeatureFileContentTest() {

        String expectedOutput = "@featureTag1\n" +
                "@featureTag2\n" +
                "Feature: featureName\n" +
                "\n" +
                "@scenarioTag1\n" +
                "@scenarioTag2\n" +
                "Scenario: scenarioName\n" +
                "\n" +
                "Step 1\n" +
                "Step 2\n" +
                "\n" +
                "# Generated by Cucable\n";

        String featureName = "featureName";
        List<String> featureTags = Arrays.asList("@featureTag1", "@featureTag2");
        String scenarioName = "scenarioName";
        List<Step> backgroundSteps = Arrays.asList(
                new Step("Step 1", null),
                new Step("Step 2", null)
        );
        List<String> scenarioTags = Arrays.asList("@scenarioTag1", "@scenarioTag2");

        SingleScenario singleScenario = new SingleScenario(featureName, scenarioName, featureTags, backgroundSteps);
        singleScenario.setScenarioTags(scenarioTags);

        String renderedFeatureFileContent = featureFileContentRenderer.getRenderedFeatureFileContent(singleScenario);

        assertThat(renderedFeatureFileContent, is(expectedOutput));
    }
}