/*
 * Copyright 2017 trivago N.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.trivago.rta.runners;

import com.trivago.rta.exceptions.filesystem.MissingFileException;
import com.trivago.rta.files.FileIO;
import com.trivago.rta.vo.SingleScenarioRunner;

import javax.inject.Inject;
import javax.inject.Singleton;

@Singleton
public class RunnerFileContentRenderer {

    // Template variable that needs to be replaced by the real feature file name inside the runner template.
    private static final String FEATURE_FILE_NAME_PLACEHOLDER = "[FEATURE_FILE_NAME]";

    private final FileIO fileIO;

    @Inject
    public RunnerFileContentRenderer(FileIO fileIO) {
        this.fileIO = fileIO;
    }

    /**
     * Returns the full content for the concrete runner file.
     *
     * @return The file content for the runner file.
     * @throws MissingFileException Thrown if the runner file is missing.
     */
    public String getRenderedRunnerFileContent(SingleScenarioRunner singleScenarioRunner) throws MissingFileException {
        String fileString;
        fileString = fileIO.readContentFromFile(singleScenarioRunner.getRunnerTemplatePath());
        fileString = fileString.replace(FEATURE_FILE_NAME_PLACEHOLDER, singleScenarioRunner.getFeatureFileName());
        fileString = addCucableComment(fileString);
        return fileString;
    }

    /**
     * Adds the "Generated by Cucable" message to a string.
     *
     * @param source The source string.
     * @return The new string with the Cucable message attached.
     */
    private String addCucableComment(final String source) {
        return source.concat(System.lineSeparator()
                + "// Generated by Cucable" + System.lineSeparator());
    }

}
