package com.trivago.rta.files;

import com.trivago.rta.vo.SingleScenarioFeature;

import java.util.Date;

public class FeatureFileContentRenderer {

    /**
     * Get the complete content that can be written to a valid feature file.
     *
     * @return the feature file content.
     */
    public String getRenderedFeatureFileContent(SingleScenarioFeature singleScenarioFeature) {
        StringBuilder renderedContent = new StringBuilder();

        // add feature name
        renderedContent
                .append("Feature: ").append(singleScenarioFeature.getFeatureName())
                .append(System.lineSeparator()).append(System.lineSeparator());

        // add tags
        for (String tag : singleScenarioFeature.getTags()) {
            renderedContent.append(tag).append(System.lineSeparator());
        }

        // add scenario name with keywords
        renderedContent.append("Scenario: ")
                .append(singleScenarioFeature.getName()).append(System.lineSeparator());

        // add steps
        for (int i = 0; i < singleScenarioFeature.getSteps().size(); i++) {
            renderedContent.append(singleScenarioFeature.getKeywords().get(i)).append(" ")
                    .append(singleScenarioFeature.getSteps().get(i)).append(System.lineSeparator());
        }

        renderedContent.append(System.lineSeparator())
                .append("# Generated by Cucable, ").append(new Date())
                .append(System.lineSeparator());

        return renderedContent.toString();
    }
}
