package com.trivago.rta.files;

import com.trivago.rta.exceptions.filesystem.MissingFileException;
import com.trivago.rta.vo.SingleScenarioRunner;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Paths;
import java.util.Date;

import static java.nio.file.Files.readAllBytes;

public class RunnerFileContentRenderer {

    // Template variable that needs to be replaced by the real feature file name inside the runner template.
    private static final String FEATURE_FILE_NAME_PLACEHOLDER = "[FEATURE_FILE_NAME]";

    /**
     * Returns the full content for the concrete runner file.
     *
     * @return The file content for the runner file.
     * @throws MissingFileException Thrown if the runner file is missing.
     */
    public String getRenderedRunnerFileContent(SingleScenarioRunner singleScenarioRunner) throws MissingFileException {
        String fileString;
        try {
            fileString = new String(
                    readAllBytes(
                            Paths.get(singleScenarioRunner.getRunnerTemplatePath())),
                    StandardCharsets.UTF_8);
            fileString = fileString.replace(FEATURE_FILE_NAME_PLACEHOLDER, singleScenarioRunner.getFeatureFileName());
            fileString = addCucableComment(fileString);
        } catch (IOException e) {
            throw new MissingFileException(singleScenarioRunner.getRunnerTemplatePath());
        }
        return fileString;
    }

    /**
     * Adds the "Generated by Cucable" message to a string.
     *
     * @param source The source string.
     * @return The new string with the Cucable message attached.
     */
    private String addCucableComment(final String source) {
        return source.concat(System.lineSeparator()
                + "// Generated by Cucable, "
                + new Date() + System.lineSeparator());
    }

}
